auto:
  notifications:
    chat:
      main:
        delay: 10
        prefix: '[Test]'
        messages:
          - 'Govno!'
          - 'Daun!'
        permission: true
    advancement:
      main2:
        delay: 10
        messages:
          - icon: 'minecraft:diamond'
            header: 'Привет!'
            footer: 'Спасибо, что играешь на сервере Infinity!'
          - icon: 'minecraft:gold_ingot'
            header: 'Тех.поддержка'
            footer: 'vk.com/thematdev'
        permission: true
    