auto:
  notifications:
    chat:
      main:
        delay: 10
        prefix: '[Test]'
        messages:
          - 'Test!'
          - 'Test2!'
        permission: true
    advancement:
      main:
        delay: 10
        messages:
          - icon: 'minecraft:diamond'
            header: 'Hi!'
            footer: 'Thanks for using ChatManager by thematdev'
          - icon: 'minecraft:gold_ingot'
            header: 'Support'
            footer: 'vk.com/thematdev'
        permission: true
    