auto:
  notifications:
    chat:
      main:
        delay: 10
        prefix: '[Test]'
        messages:
          - 'Govno!'
          - 'Daun!'
        permission: true
    advancement:
      main2:
        delay: 10
        messages:
          - icon: 'minecraft:diamond'
            header: '228'
            footer: '228'
          - icon: 'minecraft:gold_ingot'
            header: 'gay'
            footer: 'gay'
        permission: true
    