auto:
  notifications:
    chat:
      main:
        delay: 10
        prefix: '&2[ChatManager by thematdev]'
        messages:
          - 'This server is using ChatManager'
          - 'github.com/thematdev/ChatManager'
        permission: true
    advancement:
      main:
        delay: 10
        messages:
          - icon: 'minecraft:bedrock'
            header: 'Advancements is simple...'
            footer: 'Just use ChatManager'
          - icon: 'minecraft:gold_ingot'
            header: 'thematdev'
            footer: 'Write ChatManager'
        permission: true