auto:
  notifications:
    chat:
      main:
        delay: 10
        prefix: '[Test]'
        messages:
          - 'Test!'
          - 'Test2!'
        permission: true
    advancement:
      main:
        delay: 10
        messages:
          - icon: 'minecraft:bedrock'
            header: 'This is...'
            footer: 'ChatManager plugin by thematdev'
          - icon: 'minecraft:gold_ingot'
            header: 'Donate us!'
            footer: 'vk.com/thematdev'
        permission: true
    