api-version: 1.13
name: Cm
version: ALPHA 5.0.3
main: ru.thematdev.cm.main.Main
description: ChatManager for Minecraft 1.13-1.132
author: thematdev
commands:
  chat:
    usage: /<command> <arg1>
    aliases: [cm]
  automessage:
    usage: /<command> <arg1>
    aliases: [am]